### ISSUE TITLE
Roadmap: Swoole Library 5.2

### ISSUE THREAD

**Issue by deminy** [swoole/library#165]
## Changed

- [x] Refactor method `\Swoole\Database\PDOStatementProxy::setFetchMode()`.
- [x] Refactor method `\Swoole\MultibyteStringObject::substr()`.
- [x] Refactor method `\Swoole\FastCGI\Message::withBody()` from `public function withBody($body): self;` to `public function withBody(string|\Stringable $body): self;`.
- [x] Fix method `\Swoole\MultibyteStringObject::chunk()`, and update the parent method if needed.

## Miscellaneous

- [ ] Errors ignored by PHPStan (check file _./phpstan.neon.dist_ for details)

**Comment by deminy** [comment]
MR https://github.com/swoole/swoole-src/pull/5255 submitted. Closing issue.
